[package]
name = "btracker-fs"
version = "0.2.0"
edition = "2024"
license = "MIT"
readme = "README.md"
description = "Shared filesystem API for the βtracker project components"
keywords = ["btracker", "bittorrent", "aquatic-crawler", "librqbit", "database"]
categories = ["network-programming"]
repository = "https://github.com/yggverse/btracker-fs"
# homepage = "https://yggverse.github.io"

[features]
# default = ["public"]
public = []

[dependencies]
chrono = { version = "0.4.41", features = ["serde"] }
librqbit-core = "5.0.0"